FROM ubuntu-ping
RUN apt update
RUN apt -y install python3
WORKDIR /root
RUN echo "<html><head></head><body><h1>Conexion realizada con exito</h1></body></html>" > /root/index.html
CMD ["python3", "-m", "http.server", "80"]